algoritmo "Analisador de Valores"
var
   A1: Inteiro
   A2, A3, A4, A5, Soma, Media, Pares: Real
inicio
  Soma <- 0
   Para A1 <- 1 ate 5 faca
   Escreva ("Digite o ", A1, "º Valor: ")
   Leia(A3)
   Soma <- Soma + A3
   Fimpara
   Media <- Soma/5
   Escreval ("A Soma de todos os valores é: ", Soma)
   Escreval ("A media dos valores é de: ", Media)

   
   
   
   


fimalgoritmo